Grammar check + suggestions
EdwardLangdon/privacyguides.org pull request #2
Opened 2022-06-05 10:37 UTC by noClaps

Hey,

I've corrected and reworded a few things, and made a few suggestions. Look through it, and add your commits to this PR as necessary, and merge when you're done.

Cheers!

2022-06-05 11:17 UTC, EdwardLangdon requested changes

2022-06-05 11:17 UTC, EdwardLangdon commented on docs/windows/hardening.md
> +After you have installed Windows, turn on Full Disk Encryption (FDE) using BitLocker from Control Panel instead of Settings. This is because Microsoft designed it in a way that the encryption keys fo
I have a comment in the actual issue. Will add it after merging.

2022-06-05 11:17 UTC, EdwardLangdon commented on docs/windows/hardening.md
> +As you are using Windows 11, TPM is used to encrypt and decrypt the drive but it is susceptible to [cold boot attacks](https://blog.elcomsoft.com/2021/01/understanding-bitlocker-tpm-protection/). So,
Well, If you open Group Policy editor by searching in the Windows search menu from Taskbar. 

You will see the Computer configuration in the window that open up

2022-06-05 11:17 UTC, EdwardLangdon commented on docs/windows/hardening.md
> +<!-- Your path is too long, if there's a shorter way to get here, use that instead -->
It's totally GUI based thing. So, There is no other way to open it shortly.

2022-06-05 11:17 UTC, EdwardLangdon commented on docs/windows/overview.md
> +    This guide will be mostly focused on Windows 11 but you can apply this to Windows 10 too as both share the same Source Code at the core.
add 

*[GP]: Group Policy at the end.

2022-06-05 11:19 UTC, noClaps commented on docs/windows/hardening.md
> +As you are using Windows 11, TPM is used to encrypt and decrypt the drive but it is susceptible to [cold boot attacks](https://blog.elcomsoft.com/2021/01/understanding-bitlocker-tpm-protection/). So,
Well explain that. This is what I mean when I said you need step-by-step instructions. Not everyone will know how to get to these settings. A link to a site that clearly explains how to get to that location and what settings to change is also perfectly fine.

2022-06-05 11:20 UTC, noClaps commented on docs/windows/hardening.md
> +<!-- Your path is too long, if there's a shorter way to get here, use that instead -->
Hmm alright, there's not much we can do about that then.

2022-06-05 11:21 UTC, EdwardLangdon commented on docs/windows/hardening.md
> +As you are using Windows 11, TPM is used to encrypt and decrypt the drive but it is susceptible to [cold boot attacks](https://blog.elcomsoft.com/2021/01/understanding-bitlocker-tpm-protection/). So,
Okay, I will.

2022-06-05 11:22 UTC, noClaps commented on docs/windows/overview.md
> +    This guide will be mostly focused on Windows 11 but you can apply this to Windows 10 too as both share the same Source Code at the core.
For this line specifically, I'd probably put something about the Windows NT core instead of just mentioning "Source Code"

2022-06-05 11:22 UTC, noClaps commented on docs/windows/overview.md
> +    This guide will be mostly focused on Windows 11 but you can apply this to Windows 10 too as both share the same Source Code at the core.
And a link to the Wikipedia article for Windows NT

2022-06-05 11:23 UTC, EdwardLangdon commented on docs/windows/overview.md
> +    This guide will be mostly focused on Windows 11 but you can apply this to Windows 10 too as both share the same Source Code at the core.
Okay.

2022-06-05 11:29 UTC, noClaps commented on docs/windows/hardening.md
> +<!-- Your path is too long, if there's a shorter way to get here, use that instead -->
I'll mark this as resolved then.

2022-06-05 13:58 UTC, merged

2022-06-06 13:34 UTC, EdwardLangdon commented on docs/windows/hardening.md
> +After you have installed Windows, turn on Full Disk Encryption (FDE) using BitLocker from Control Panel instead of Settings. This is because Microsoft designed it in a way that the encryption keys fo
I added this